# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MDKN Derlemesi

on:
  push:
    branches: [ "main" ]
    
permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none

jobs:
  
  derleme:

    runs-on: ubuntu-latest
    permissions: 
      issues: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: NodeJS Yapılandırılıyor..
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: NPM  Yönetimi
      run: node -v
    - name: Bağımlılıklar kuruluyor..
      run: npm install
    - name: axios@mdkn indiriliyor..
      run: npm i axios
    - name: tailwind@nuxtjs indiriliyor..
      run: npm install --save-dev @nuxtjs/tailwindcss
    - name: gh-pages@mdkn indiriliyor..
      run: npm i gh-pages
    - name: Derleme süreci..
      run: npm run generate
    - name: main ls
      run: ls
    - name: path
      run: echo $PWD
    - name: Ayarlamalar..
      run: echo "NOW=$(date +'%m-%d-%Y, '%T'')" >> $GITHUB_ENV
    - name: Bildiri yayınlanması
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "New Changes - '"$NOW"'",
          "body": "New changes have been made on **account.macesdev.net** site, if you re experiencing errors, you better check it out!. \n\n _Update Logs_ (${{ github.sha }} by **@mamiiblt**). \n\n ```${{github.event.commits[0].message}}```",
          "labels":["new-update"]
        }' \
        --fail
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

