# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: MDKN Derlemesi

on:
  push:
    branches: [ "main" ]

jobs:
  
  derleme:

    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
      contents: write
      repository-projects: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: NodeJS Yapılandırılıyor..
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: NPM  Yönetimi
      run: node -v
    - name: Bağımlılıklar kuruluyor..
      run: npm install
    - name: axios@mdkn indiriliyor..
      run: npm i axios
    - name: tailwind@nuxtjs indiriliyor..
      run: npm install --save-dev @nuxtjs/tailwindcss
    - name: gh-pages@mdkn indiriliyor..
      run: npm i gh-pages
    - name: main ls
      run: ls
    - name: Derleme süreci..
      run: npm run generate

    - name: gen ls
      run: ls /home/runner/work/mnet-preview/mnet-preview/.output/public/
    - name: Ayarlamalar..
      run: echo "NOW=$(date +'%m-%d-%Y, '%T'')" >> $GITHUB_ENV
    - name: Bildiri yayınlanması
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "New Changes - '"$NOW"'",
          "body": "New changes have been made on **account.macesdev.net** site, if you re experiencing errors, you better check it out!. \n\n _Update Logs_ (${{ github.sha }} by **@mamiiblt**). \n\n ```${{github.event.commits[0].message}}```",
          "labels":["new-update"]
        }' \
        --fail
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Yayına alma..
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        user_name: 'macesdev-mdkn[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'mdkn@autodeploy : $NOW'
        publish_branch: gh-pages
